HTTPException Error, Response Body Example added
codeforcauseorg/edu-server pull request #38
Opened 2021-03-26 20:30 UTC by shivambhatia5432

**Description**
- I have added Response Examples for few requests.
- Added HTMLExcepmtion instead of Internal Server Error if user not found
- Request at user/user/:userID changes to user/:userID

**Type of Change:**

- [ ] Code
- [ ] New Feature

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] My changes generate no new warnings
- [x] The title of my pull request is a short description of the requested changes.

**Screenshots**
   Original                 |   Updated
  :------------------------:|---------------------:
![Screenshot 2021-03-27 at 1 55 13 AM](https://user-images.githubusercontent.com/50217679/112688868-7d6a6100-8e9f-11eb-95fd-ae606002be5b.png) | ![Screenshot 2021-03-27 at 1 53 37 AM](https://user-images.githubusercontent.com/50217679/112688751-4b58ff00-8e9f-11eb-8ed2-fe4683147a49.png)

2021-03-26 20:34 UTC, shivambhatia5432 commented
@Abhishek-kumar09 Please have a look at this PR, I will be happy to make changes if there are any

2021-03-26 20:53 UTC, Abhishek-kumar09 requested changes
Revert changes of package-lock.json since no more additions in package

2021-03-26 20:53 UTC, Abhishek-kumar09 commented on src/user/user.service.ts
> +    if (User) {
Please also rename `User` to `user`

2021-03-26 21:26 UTC, shivambhatia5432 commented
@Abhishek-kumar09 Changes requested implemented

2021-03-27 12:06 UTC, merged

2021-03-27 12:06 UTC, Abhishek-kumar09 commented
Thanks @shivambhatia5432