Minor changes in DTOs and validation, API Tags
codeforcauseorg/edu-server pull request #56
Opened 2021-05-01 19:35 UTC by shivambhatia5432

**Description**

Minor changes in DTOs and validation, API Tags

**Related Issue** 
- issue goes here

Fixes # [ISSUE]

- [x] Code
- [ ] User Interface
- [ ] New Feature
- [ ] Documentation
- [ ] Testing

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My UI is responsive
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] My changes generate no new warnings
- [ ] The title of my pull request is a short description of the requested changes.

2021-05-01 20:21 UTC, Devesh21700Kumar reviewed
Hey @shivambhatia5432 
Actually, the validation pipe is not being set up globally and is only being used in instances such as the creation of a new object, or creations of a user in other endpoint sets of controllers for other schemas.

So I think you may remove those changes to the main.ts file.

2021-05-01 21:19 UTC, shivambhatia5432 commented
Done @Devesh21700Kumar thank you so much man for helping

2021-05-04 06:55 UTC, Abhishek-kumar09 commented
Please resolve merge conflicts.

2021-05-04 09:55 UTC, shivambhatia5432 commented
> Please resolve merge conflicts.

Done

2021-05-04 18:31 UTC, Abhishek-kumar09 requested changes
It gone unnoticed during previous review but please change `submit_by` to string that will contain user's `_id`
https://github.com/codeforcauseorg/edu-server/blob/55c096e96d99e2fb2fa319662be9d1e1f019b1bd/src/schemas/assignment.schema.ts#L18

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/assignment/assignment.controller.ts
> +  @Length(3, 20)
The class validators will have no effect here, Please remove the class validators from the swagger response body.

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/assignment/assignment.controller.ts
>    id: string;
`id` to `_id`

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/assignment/assignment.controller.ts
>    @ApiProperty({ required: true, example: 'noobcoder@gmai.com' })
`noobcoder@gmail.com`

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/chat/chat.controller.ts
> +  @ApiProperty({ required: true, example: 'noob2' })
please revert this.

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/chat/chat.controller.ts
> +import { ApiCreatedResponse, ApiProperty, ApiTags } from '@nestjs/swagger';
Please keep that line on the same linenumber

2021-05-04 18:31 UTC, Abhishek-kumar09 commented on src/modules/user/user.controller.ts
> +  @IsEmail()
These classvalidators have no effect on the doc I guess

2021-05-07 11:36 UTC, shivambhatia5432 commented
> It gone unnoticed during previous review but please change `submit_by` to `User` that will contain user's `_id`
> https://github.com/codeforcauseorg/edu-server/blob/55c096e96d99e2fb2fa319662be9d1e1f019b1bd/src/schemas/assignment.schema.ts#L18

What is submit_by format in actual? In assignment.schema it is number and in assignment.controller it is string

2021-05-07 18:14 UTC, Abhishek-kumar09 commented
> > It gone unnoticed during previous review but please change `submit_by` to `User` that will contain user's `_id`
> > https://github.com/codeforcauseorg/edu-server/blob/55c096e96d99e2fb2fa319662be9d1e1f019b1bd/src/schemas/assignment.schema.ts#L18
> 
> What is submit_by format in actual? In assignment.schema it is number and in assignment.controller it is string


It will be actually mongoId. so it should be `string`. You can decorate that with `@IsMongoId` in the Dto.

2021-09-08 06:32 UTC, closed without merging